- name: Remove existing Helm binary if exists
  file:
    path: /usr/local/bin/helm
    state: absent

- name: Download Helm binary
  get_url:
    url: "https://get.helm.sh/helm-v3.12.0-linux-amd64.tar.gz"
    dest: "/tmp/helm.tar.gz"
    mode: '0644'

- name: Extract Helm binary
  unarchive:
    src: "/tmp/helm.tar.gz"
    dest: "/tmp/"
    remote_src: yes

- name: Move Helm binary to /usr/local/bin
  command: mv /tmp/linux-amd64/helm /usr/local/bin/helm
  args:
    creates: /usr/local/bin/helm

- name: Ensure Helm is executable
  file:
    path: /usr/local/bin/helm
    mode: '0755'
