- name: Generate Redis password
  shell: openssl rand -hex 16
  register: redis_password

- name: Ensure ArgoCD directory exists
  file:
    path: /tmp/argo-cd
    state: directory

- name: Update values.yaml with generated passwords
  template:
    src: templates/argocd-values.yaml.j2
    dest: /tmp/argo-cd/values.yaml

- name: Install ArgoCD using Helm
  shell: >
    helm upgrade --install argocd /tmp/argo-cd
    --namespace argocd
    -f /tmp/argo-cd/values.yaml
