- name: Ensure ArgoCD is not already installed
  hosts: master
  become: yes
  tasks:
    - name: Check if ArgoCD namespace exists
      command: kubectl get namespace argocd
      register: argocd_namespace
      ignore_errors: yes

    - name: Delete existing ArgoCD namespace if it exists
      command: kubectl delete namespace argocd --ignore-not-found=true
      when: argocd_namespace.rc == 0

    - name: Remove existing ArgoCD ClusterRole
      command: kubectl delete clusterrole argocd-application-controller --ignore-not-found=true
      ignore_errors: yes

    - name: Remove existing ArgoCD ClusterRoleBinding
      command: kubectl delete clusterrolebinding argocd-application-controller --ignore-not-found=true
      ignore_errors: yes

- name: Install ArgoCD via Helm
  hosts: master
  become: yes
  tasks:
    - name: Add Argo Helm repository
      command: helm repo add argo https://argoproj.github.io/argo-helm

    - name: Update Helm repositories
      command: helm repo update

    - name: Install ArgoCD with Helm
      command: helm upgrade --install argocd argo/argo-cd -n argocd --create-namespace