name: Deploy ArgoCD to Kubernetes

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Configure Kubeconfig
        run: echo "${{ secrets.KUBECONFIG }}" | base64 --decode > kubeconfig

      - name: Run Ansible Playbook to Deploy ArgoCD
        env:
          KUBECONFIG: kubeconfig
        run: ansible-playbook -i inventory.ini playbook/gitops.yml -vv

      - name: Wait for ArgoCD server to be ready
        run: kubectl wait --for=condition=available --timeout=600s deployment/argocd-server -n argocd -vv

      - name: Retrieve ArgoCD admin password
        run: |
          echo "ArgoCD Admin Password: $(kubectl get secret argocd-initial-admin-secret -n argocd -o jsonpath='{.data.password}' | base64 --decode)" -vv

