name: Deploy to Kubernetes

on:
  push:
    branches:
      - main  
  workflow_dispatch:  

jobs:
  deploy:
    runs-on: self-hosted  
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Ensure roles directory exists
        run: mkdir -p playbook/roles

      - name: Check if requirements.yml exists
        id: check_requirements
        run: |
          if [ ! -f "playbook/roles/requirements.yml" ]; then
            echo "Generating requirements.yml..."
            cat <<EOF > playbook/roles/requirements.yml
          ---
          roles:
            - name: argocd
              src: git+https://github.com/argoproj/argocd-ansible.git
          EOF
          fi

      - name: Install Ansible Roles
        run: ansible-galaxy install -r playbook/roles/requirements.yml

      - name: Run Ansible Playbook
        run: ansible-playbook -i .github/workflows/inventory.ini playbook/gitops-deploy.yml

