name: Deploy ArgoCD with Ansible

on:
  push:
    branches:
      - main  # main 브랜치에 push할 때 실행

jobs:
  deploy:
    runs-on: self-hosted  # 192.168.1.172 서버에서 실행
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run Ansible Playbook to Install Helm
        run: ansible-playbook -i inventory.ini playbooks/install_helm.yml -vv

      - name: Ensure ArgoCD Helm Chart is Downloaded
        run: ansible-playbook -i inventory.ini playbooks/download_argocd_chart.yml -vv

      - name: Install ArgoCD using Helm
        run: ansible-playbook -i inventory.ini playbooks/install_argocd.yml -vv
