name: Deploy ArgoCD with Ansible

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted  # 사내망에서 사용하는 Runner

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Debug files
        run: ls -la .github/workflows/ && cat .github/workflows/inventory.ini || echo "inventory.ini not found"

      - name: Copy inventory file
        run: cp .github/workflows/inventory.ini inventory.ini

      - name: Configure Kubeconfig
        run: echo "${{ secrets.KUBECONFIG }}" | base64 --decode > kubeconfig

      - name: Run Ansible Playbook to Deploy ArgoCD
        env:
          KUBECONFIG: kubeconfig
        run: ansible-playbook -i inventory.ini playbook/configure_argocd.yml -vv

      - name: Wait for ArgoCD server to be ready
        env:
          KUBECONFIG: kubeconfig
        run: kubectl wait --for=condition=available --timeout=600s deployment/argocd-server -n argocd

      - name: Retrieve ArgoCD admin password
        env:
          KUBECONFIG: kubeconfig
        run: |
          echo "ArgoCD Admin Password: $(kubectl get secret argocd-initial-admin-secret -n argocd -o jsonpath='{.data.password}' | base64 --decode)"
