name: Deploy to Kubernetes

on:
  push:
    branches:
      - main  
  workflow_dispatch:  

jobs:
  deploy:
    runs-on: self-hosted  
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Run Ansible Playbook 배포
        run: ansible-playbook -i /home/runner/actions-runner/_work/gitops-k8s-deploy/gitops-k8s-deploy/inventory.ini playbook/gitops-deploy.yml

