name: Deploy to ArgoCD

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set ArgoCD Server
        run: echo "ARGOCD_SERVER=192.168.1.142:32384" >> $GITHUB_ENV

      - name: Set ArgoCD Environment Variables
        run: echo "ARGOCD_OPTS=--insecure" >> $GITHUB_ENV

      - name: ArgoCD Login
        run: |
          argocd login $ARGOCD_SERVER --username admin --password ${{ secrets.ARGOCD_PASSWORD }}

      - name: Sync ArgoCD Application
        run: |
          argocd app sync my-app
